### ISSUE TITLE
Actual encryption password

### ISSUE THREAD

**Issue by dfrazao** [rodriguestiago0/actual-mealcards#8]
Hi @rodriguestiago0 ,
 
My finances file is encrypted, and when I run the importer it gives an error and asks, understandably, for the encription pasword. 
Is there an enviroment variable for it tha I'm missing? Looking at env.sample there doesn't seem to be :/

Could you help me out? 
Thanks!

**Comment by rodriguestiago0** [comment]
I will create a fix for it.

**Comment by dfrazao** [comment]
Thanks! I use Coverflex, if you need any help for testing lmk!

**Comment by rodriguestiago0** [comment]
done

**Comment by dfrazao** [comment]
Hey, I've tested it today but still getting an error related to it: 

<img width="1221" alt="Image" src="https://github.com/user-attachments/assets/b3e835c3-f3e2-4119-b08f-40d42b589c4c" />

I've tried filling the var ACTUAL_FILE_PASSWORD with the correct password, a random string, and with it empty and I always get the same error..

**Comment by rodriguestiago0** [comment]
Check latest version please

**Comment by rodriguestiago0** [comment]
Obrigado.
